version: "3.8"
services:
  DB:
    image: postgres:14
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank_api
    ports:
      - "5432:5432"
    volumes:
      - ./db_creation.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050